os: osx
language: objective-c

before_install:

   - openssl aes-256-cbc -K $encrypted_a55725af6cd1_key -iv $encrypted_a55725af6cd1_iv -in test_credentials.json.enc -out test_credentials.json -d

script:
   - xctool -project test/test.xcodeproj
